version: '3'
services:
  client:
    build:
      dockerfile: ./client.Docker
    privileged: true
    networks:
      bad-network:
        ipv4_address: 172.28.1.3
    entrypoint: ["sh", "-c", "tc qdisc add dev eth0 root netem delay 500ms loss 50%; /app/client"]

  server:
    build:
      dockerfile: ./server.Docker
    networks:
      bad-network:
        ipv4_address: 172.28.1.2

networks:
  bad-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.1.0/24
          gateway: 172.28.1.254